# Generated by Django 3.1.7 on 2021-04-05 11:43

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Sai định dạng số điện thoại', regex='\\+?(0|84)\\d{9}')])),
                ('image', models.URLField(max_length=500)),
                ('jackpot_keys', models.CharField(default=main.models.Candidate.get_random_number, editable=False, max_length=4, unique=True)),
            ],
        ),
    ]
